package cn.campusmind.user.controller;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.data.redis.core.ValueOperations;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import javax.crypto.SecretKey;
import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.Instant;
import java.util.Date;

import static org.springframework.http.HttpHeaders.AUTHORIZATION;
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class UserControllerTest {

    private static final String SECRET = "test-secret-key-with-at-least-32-bytes";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @MockitoBean
    private StringRedisTemplate redisTemplate;

    @MockitoBean
    private ValueOperations<String, String> valueOperations;

    @BeforeEach
    void setUp() throws Exception {
        org.mockito.Mockito.when(redisTemplate.opsForValue()).thenReturn(valueOperations);
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS `user` (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      username VARCHAR(64) NOT NULL UNIQUE,
                      phone VARCHAR(32),
                      password_hash VARCHAR(255) NOT NULL,
                      role VARCHAR(32) NOT NULL,
                      status TINYINT NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_profile (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      college VARCHAR(128),
                      major VARCHAR(128),
                      grade VARCHAR(32),
                      class_name VARCHAR(128),
                      interest_tags VARCHAR(1024),
                      course_codes VARCHAR(1024),
                      sensitivity DOUBLE DEFAULT 0.5,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("DELETE FROM user_profile");
            statement.execute("CREATE TABLE IF NOT EXISTS user_information_state (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, item_id BIGINT, read_status VARCHAR(20))");
            statement.execute("CREATE TABLE IF NOT EXISTS user_source_subscription (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, source_id BIGINT, enabled BOOLEAN)");
            statement.execute("CREATE TABLE IF NOT EXISTS user_action_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, information_item_id BIGINT, title VARCHAR(255))");
            statement.execute("CREATE TABLE IF NOT EXISTS user_reminder (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, action_item_id BIGINT, status VARCHAR(20))");
            statement.execute("CREATE TABLE IF NOT EXISTS campus_event (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_user_id BIGINT, title VARCHAR(255))");
            statement.execute("DELETE FROM user_information_state");
            statement.execute("DELETE FROM user_source_subscription");
            statement.execute("DELETE FROM user_action_item");
            statement.execute("DELETE FROM user_reminder");
            statement.execute("DELETE FROM campus_event");
            statement.execute("DELETE FROM `user`");
        }
        insertUser(1L, "alice", "13800138000", "STUDENT");
        insertUser(9901L, "admin", "13800139901", "ADMIN");
    }

    @Test
    void meReturnsCurrentUserWithMaskedPhone() throws Exception {
        mockMvc.perform(get("/api/v1/users/me")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.data.id").value(1))
                .andExpect(jsonPath("$.data.username").value("alice"))
                .andExpect(jsonPath("$.data.phone").value("138****8000"));
    }

    @Test
    void updateProfileUpsertsProfile() throws Exception {
        mockMvc.perform(put("/api/v1/users/me/profile")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {
                                  "college": "软件学院",
                                  "major": "软件工程",
                                  "grade": "2023",
                                  "className": "软件工程1班",
                                  "interestTags": ["讲座", "竞赛"],
                                  "courseCodes": ["SE101"]
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.college").value("软件学院"))
                .andExpect(jsonPath("$.data.interestTags[0]").value("讲座"))
                .andExpect(jsonPath("$.data.courseCodes[0]").value("SE101"));
    }

    @Test
    void meRejectsMissingToken() throws Exception {
        mockMvc.perform(get("/api/v1/users/me"))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.code").value("UNAUTHORIZED"));
    }

    @Test
    void adminUsersReturnsUserListForAdmin() throws Exception {
        mockMvc.perform(get("/api/v1/users/admin")
                        .header(AUTHORIZATION, bearerToken(9901L, "admin", "ADMIN")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[?(@.username=='alice')].role").value("STUDENT"))
                .andExpect(jsonPath("$.data.items[?(@.username=='admin')].role").value("ADMIN"));
    }

    @Test
    void adminUsersRejectsNonAdmin() throws Exception {
        mockMvc.perform(get("/api/v1/users/admin")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value("ADMIN_REQUIRED"));
    }

    @Test
    void adminCanCreateUserAndDisableIt() throws Exception {
        mockMvc.perform(post("/api/v1/users/admin")
                        .header(AUTHORIZATION, bearerToken(9901L, "admin", "ADMIN"))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {
                                  "username": "operator",
                                  "phone": "13800138001",
                                  "role": "OPERATOR",
                                  "password": "123456"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.username").value("operator"))
                .andExpect(jsonPath("$.data.role").value("OPERATOR"));

        mockMvc.perform(put("/api/v1/users/admin/1/status")
                        .header(AUTHORIZATION, bearerToken(9901L, "admin", "ADMIN"))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {
                                  "status": 0
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.status").value(0));
    }

    @Test
    void adminCanResetPassword() throws Exception {
        mockMvc.perform(put("/api/v1/users/admin/1/password")
                        .header(AUTHORIZATION, bearerToken(9901L, "admin", "ADMIN"))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {
                                  "password": "654321"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.username").value("alice"));
    }

    @Test
    void userCanExportAndDeleteOwnAccount() throws Exception {
        mockMvc.perform(get("/api/v1/users/me/export")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.account.phone").value("13800138000"))
                .andExpect(jsonPath("$.data.informationStates").isArray());

        mockMvc.perform(delete("/api/v1/users/me")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"password":"password123"}
                                """))
                .andExpect(status().isOk());

        mockMvc.perform(get("/api/v1/users/me")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.status").value(0))
                .andExpect(jsonPath("$.data.phone").doesNotExist());
    }

    private void insertUser(Long id, String username, String phone, String role) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO `user` (id, username, phone, password_hash, role, status)
                     VALUES (?, ?, ?, ?, ?, 1)
                     """)) {
            statement.setLong(1, id);
            statement.setString(2, username);
            statement.setString(3, phone);
            statement.setString(4, new BCryptPasswordEncoder().encode("password123"));
            statement.setString(5, role);
            statement.executeUpdate();
        }
    }

    private static String bearerToken(Long userId, String username, String role) {
        Instant now = Instant.now();
        SecretKey key = Keys.hmacShaKeyFor(SECRET.getBytes(StandardCharsets.UTF_8));
        String token = Jwts.builder()
                .issuer("campusmind-auth-test")
                .subject(String.valueOf(userId))
                .claim("username", username)
                .claim("role", role)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plusSeconds(3600)))
                .signWith(key)
                .compact();
        return "Bearer " + token;
    }
}
