server:
  port: 8082

spring:
  application:
    name: campus-user-service
  datasource:
    url: ${USER_DB_URL:jdbc:mysql://localhost:3306/campusmind?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}

campus:
  auth:
    jwt:
      issuer: ${AUTH_JWT_ISSUER:campusmind-auth}
      secret: ${AUTH_JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
