server:
  port: 8083

spring:
  application:
    name: campus-event-service
  datasource:
    url: ${EVENT_DB_URL:jdbc:mysql://localhost:3306/campusmind?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${EVENT_DB_USERNAME}
    password: ${EVENT_DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info
