package cn.campusmind.search.controller;

import cn.campusmind.search.application.DecisionClient;
import cn.campusmind.search.application.DecisionPlan;
import cn.campusmind.common.web.ApiResponse;
import cn.campusmind.search.feign.VectorSearchFeignClient;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import javax.crypto.SecretKey;
import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;
import java.util.Map;

import static org.mockito.ArgumentMatchers.anyBoolean;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.when;
import static org.springframework.http.HttpHeaders.AUTHORIZATION;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class SearchControllerTest {

    private static final String SECRET = "test-secret-key-with-at-least-32-bytes";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @MockBean
    private DecisionClient decisionClient;

    @MockBean
    private VectorSearchFeignClient vectorSearchFeignClient;

    @BeforeEach
    void setUp() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS campus_event (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      summary CLOB,
                      event_type VARCHAR(64) NOT NULL,
                      source_type VARCHAR(64) NOT NULL,
                      status VARCHAR(32) NOT NULL,
                      start_time TIMESTAMP,
                      end_time TIMESTAMP,
                      location VARCHAR(255),
                      organizer VARCHAR(255),
                      target_scope VARCHAR(1024),
                      tags VARCHAR(1024),
                      dedup_key CHAR(64),
                      vector_doc_id VARCHAR(128),
                      published_at TIMESTAMP,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_profile (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      college VARCHAR(128),
                      major VARCHAR(128),
                      grade VARCHAR(32),
                      class_name VARCHAR(128),
                      interest_tags VARCHAR(1024),
                      course_codes VARCHAR(1024),
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("DELETE FROM campus_event");
            statement.execute("ALTER TABLE campus_event ADD COLUMN IF NOT EXISTS visibility VARCHAR(16) DEFAULT 'PUBLIC'");
            statement.execute("ALTER TABLE campus_event ADD COLUMN IF NOT EXISTS owner_user_id BIGINT");
            statement.execute("DELETE FROM user_profile");
        }
    }

    @Test
    void feedQueryReturnsEventsByType() throws Exception {
        insertEvent("AI讲座通知", "软件学院AI讲座", "LECTURE", "AI_PUBLISHED", "2026-07-09 19:00:00");
        insertEvent("期末考试安排", "期末考试", "EXAM", "REVIEWED", "2026-07-15 09:00:00");
        when(decisionClient.plan(anyString(), anyList(), anyBoolean()))
                .thenReturn(new DecisionPlan("FEED_QUERY", List.of("LECTURE"), "ANY", List.of(), false, false, 20));

        mockMvc.perform(get("/api/v1/search")
                        .param("query", "本周讲座")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.intent").value("FEED_QUERY"))
                .andExpect(jsonPath("$.data.total").value(1))
                .andExpect(jsonPath("$.data.items[0].eventType").value("LECTURE"))
                .andExpect(jsonPath("$.data.items[0].aiPredicted").value(true));
    }

    @Test
    void semanticSearchFallsBackToKeyword() throws Exception {
        insertEvent("人工智能讲座通知", "AI主题分享", "LECTURE", "AI_PUBLISHED", "2026-07-09 19:00:00");
        when(decisionClient.plan(anyString(), anyList(), anyBoolean()))
                .thenReturn(new DecisionPlan("SEMANTIC_SEARCH", List.of(), "ANY", List.of(), true, false, 10));

        mockMvc.perform(get("/api/v1/search")
                        .param("query", "人工智能")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.intent").value("SEMANTIC_SEARCH"))
                .andExpect(jsonPath("$.data.total").value(1))
                .andExpect(jsonPath("$.data.items[0].title").value("人工智能讲座通知"))
                .andExpect(jsonPath("$.data.mode").value("KEYWORD"))
                .andExpect(jsonPath("$.data.fallback").value(true));
    }

    @Test
    void semanticSearchUsesVectorHitsAndPreservesRank() throws Exception {
        long firstId = insertEvent("数据库比赛", "数据库设计", "COMPETITION", "AI_PUBLISHED", "2026-07-09 19:00:00");
        long secondId = insertEvent("算法比赛", "算法竞赛", "COMPETITION", "AI_PUBLISHED", "2026-07-10 19:00:00");
        setVectorDocId(firstId, "event-db");
        setVectorDocId(secondId, "event-algorithm");
        when(decisionClient.plan(anyString(), anyList(), anyBoolean()))
                .thenReturn(new DecisionPlan("SEMANTIC_SEARCH", List.of(), "ANY", List.of(), true, false, 10));
        when(vectorSearchFeignClient.search(org.mockito.ArgumentMatchers.anyMap()))
                .thenReturn(ApiResponse.ok(new VectorSearchFeignClient.VectorSearchResult(List.of(
                        new VectorSearchFeignClient.VectorHit("event-algorithm", "", 0.93, Map.of()),
                        new VectorSearchFeignClient.VectorHit("event-db", "", 0.82, Map.of())
                ), 2)));

        mockMvc.perform(get("/api/v1/search")
                        .param("query", "适合我的编程竞赛")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.total").value(2))
                .andExpect(jsonPath("$.data.items[0].title").value("算法比赛"))
                .andExpect(jsonPath("$.data.items[1].title").value("数据库比赛"))
                .andExpect(jsonPath("$.data.mode").value("SEMANTIC"))
                .andExpect(jsonPath("$.data.fallback").value(false))
                .andExpect(jsonPath("$.data.items[0].score").value(0.93))
                .andExpect(jsonPath("$.data.items[0].matchedBy").value("VECTOR"));
    }

    @Test
    void personalScheduleReturnsUpcomingEvents() throws Exception {
        insertEvent("明天的作业截止", "实验报告提交", "HOMEWORK", "AI_PUBLISHED",
                LocalDateTime.now().plusDays(1).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        when(decisionClient.plan(anyString(), anyList(), anyBoolean()))
                .thenReturn(new DecisionPlan("PERSONAL_SCHEDULE", List.of(), "ANY", List.of(), false, true, 20));

        mockMvc.perform(get("/api/v1/search")
                        .param("query", "我本周有哪些作业")
                        .param("usePersonalProfile", "true")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.intent").value("PERSONAL_SCHEDULE"))
                .andExpect(jsonPath("$.data.total").value(1));
    }

    @Test
    void searchDoesNotExposeAnotherUsersPrivateEvent() throws Exception {
        insertPrivateEvent("我的机器学习作业", 2L);
        when(decisionClient.plan(anyString(), anyList(), anyBoolean()))
                .thenReturn(new DecisionPlan("SEMANTIC_SEARCH", List.of(), "ANY", List.of(), true, false, 10));

        mockMvc.perform(get("/api/v1/search")
                        .param("query", "机器学习")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.total").value(0));
    }

    @Test
    void importHelpReturnsEmptyListWithHint() throws Exception {
        when(decisionClient.plan(anyString(), anyList(), anyBoolean()))
                .thenReturn(new DecisionPlan("IMPORT_HELP", List.of(), "ANY", List.of(), false, false, 10));

        mockMvc.perform(get("/api/v1/search")
                        .param("query", "怎么导入雨课堂")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.intent").value("IMPORT_HELP"))
                .andExpect(jsonPath("$.data.total").value(0))
                .andExpect(jsonPath("$.data.message").exists());
    }

    @Test
    void searchRejectsMissingToken() throws Exception {
        mockMvc.perform(get("/api/v1/search").param("query", "讲座"))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.code").value("UNAUTHORIZED"));
    }

    @Test
    void searchRejectsBlankQuery() throws Exception {
        mockMvc.perform(get("/api/v1/search")
                        .param("query", "")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("QUERY_REQUIRED"));
    }

    private long insertEvent(String title, String summary, String eventType, String status, String startTime) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO campus_event (
                       title, summary, event_type, source_type, status,
                       start_time, end_time, location, organizer, target_scope, tags, published_at
                     ) VALUES (?, ?, ?, 'PUBLIC_WEB', ?,
                       ?, TIMESTAMP '2026-07-08 21:00:00',
                       '图书馆报告厅', '软件学院', '["软件学院"]', '["AI","讲座"]',
                       TIMESTAMP '2026-07-07 10:00:00')
                     """, Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, title);
            statement.setString(2, summary);
            statement.setString(3, eventType);
            statement.setString(4, status);
            statement.setString(5, startTime);
            statement.executeUpdate();
            try (var keys = statement.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }

    private void setVectorDocId(long eventId, String vectorDocId) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(
                     "UPDATE campus_event SET vector_doc_id = ? WHERE id = ?")) {
            statement.setString(1, vectorDocId);
            statement.setLong(2, eventId);
            statement.executeUpdate();
        }
    }

    private void insertPrivateEvent(String title, Long ownerUserId) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO campus_event (
                       title, summary, event_type, source_type, status, visibility, owner_user_id, start_time, published_at
                     ) VALUES (?, '仅本人可见', 'HOMEWORK', 'RAIN_CLASSROOM', 'AI_PUBLISHED', 'PRIVATE', ?,
                       TIMESTAMP '2026-07-09 23:59:00', TIMESTAMP '2026-07-07 10:00:00')
                     """)) {
            statement.setString(1, title);
            statement.setLong(2, ownerUserId);
            statement.executeUpdate();
        }
    }

    private static String bearerToken(Long userId, String username, String role) {
        Instant now = Instant.now();
        SecretKey key = Keys.hmacShaKeyFor(SECRET.getBytes(StandardCharsets.UTF_8));
        String token = Jwts.builder()
                .issuer("campusmind-auth-test")
                .subject(String.valueOf(userId))
                .claim("username", username)
                .claim("role", role)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plusSeconds(3600)))
                .signWith(key)
                .compact();
        return "Bearer " + token;
    }
}
