package cn.campusmind.feed.controller;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class FeedControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS campus_event (
                      id BIGINT PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      summary VARCHAR(1024),
                      event_type VARCHAR(64) NOT NULL,
                      source_type VARCHAR(64) NOT NULL,
                      status VARCHAR(32) NOT NULL,
                      confidence DECIMAL(5,4) NOT NULL,
                      start_time TIMESTAMP,
                      location VARCHAR(255),
                      tags VARCHAR(1024),
                      target_scope VARCHAR(1024),
                      published_at TIMESTAMP,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_profile (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL UNIQUE,
                      college VARCHAR(128),
                      major VARCHAR(128),
                      grade VARCHAR(32),
                      interest_tags VARCHAR(1024),
                      course_codes VARCHAR(1024)
                    )
                    """);
            statement.execute("DELETE FROM campus_event");
            statement.execute("DELETE FROM user_profile");
        }
        insertProfile();
        insertEvent(1L, "人工智能讲座", "LECTURE", "AI_PUBLISHED", "[\"AI\",\"讲座\"]", "2026-07-07 10:00:00");
        insertEvent(2L, "期末考试安排", "EXAM", "REVIEWED", "[\"考试\"]", "2026-07-06 10:00:00");
        insertEvent(3L, "无效通知", "NOTICE", "REJECTED", "[\"通知\"]", "2026-07-05 10:00:00");
    }

    @Test
    void feedReturnsVisibleEventsAndRelevance() throws Exception {
        mockMvc.perform(get("/api/v1/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(2))
                .andExpect(jsonPath("$.data.items[0].title").value("人工智能讲座"))
                .andExpect(jsonPath("$.data.items[0].relevanceScore").value(20))
                .andExpect(jsonPath("$.data.hasMore").value(false));
    }

    @Test
    void feedFiltersByType() throws Exception {
        mockMvc.perform(get("/api/v1/feed")
                        .param("type", "EXAM"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(1))
                .andExpect(jsonPath("$.data.items[0].eventType").value("EXAM"));
    }

    private void insertProfile() throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO user_profile (user_id, interest_tags, course_codes)
                     VALUES (1, '[\"AI\"]', '[\"SE101\"]')
                     """)) {
            statement.executeUpdate();
        }
    }

    private void insertEvent(Long id, String title, String eventType, String status, String tags, String publishedAt) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO campus_event (
                       id, title, summary, event_type, source_type, status, confidence,
                       start_time, location, tags, target_scope, published_at
                     ) VALUES (?, ?, '摘要', ?, 'PUBLIC_WEB', ?, 0.9000,
                       TIMESTAMP '2026-07-08 19:00:00', '图书馆报告厅', ?, '[\"软件学院\"]', ?)
                     """)) {
            statement.setLong(1, id);
            statement.setString(2, title);
            statement.setString(3, eventType);
            statement.setString(4, status);
            statement.setString(5, tags);
            statement.setString(6, publishedAt);
            statement.executeUpdate();
        }
    }
}
