package cn.campusmind.feed.controller;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class InformationControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS information_item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      source_id BIGINT NOT NULL,
                      source_name VARCHAR(128) NOT NULL,
                      source_url VARCHAR(1024) NOT NULL,
                      item_url VARCHAR(1024) NOT NULL,
                      title VARCHAR(512) NOT NULL,
                      publish_time TIMESTAMP,
                      fetched_at TIMESTAMP NOT NULL,
                      detail_content CLOB NOT NULL,
                      content_hash CHAR(64) NOT NULL,
                      item_status VARCHAR(32) NOT NULL,
                      parse_status VARCHAR(32) NOT NULL,
                      parse_error VARCHAR(1024),
                      ai_status VARCHAR(32) DEFAULT 'PENDING',
                      ai_event_type VARCHAR(32),
                      ai_summary CLOB,
                      ai_card_json CLOB,
                      ai_need_review BOOLEAN DEFAULT FALSE,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_information_state (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      item_id BIGINT NOT NULL,
                      first_seen_at TIMESTAMP NOT NULL,
                      read_at TIMESTAMP,
                      favorited_at TIMESTAMP,
                      UNIQUE KEY uk_user_item_state (user_id, item_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS data_source (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(128) NOT NULL UNIQUE,
                      source_type VARCHAR(64) NOT NULL,
                      base_url VARCHAR(1024) NOT NULL,
                      crawl_interval_seconds INT NOT NULL DEFAULT 5,
                      parser_type VARCHAR(64) NOT NULL DEFAULT 'USER_PASTE',
                      enabled INT NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_source_subscription (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      source_id BIGINT NOT NULL,
                      enabled INT NOT NULL DEFAULT 1,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      UNIQUE (user_id, source_id)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_action_item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      information_item_id BIGINT NOT NULL,
                      title VARCHAR(255) NOT NULL,
                      due_at TIMESTAMP,
                      original_url VARCHAR(1024),
                      status VARCHAR(32) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      UNIQUE (user_id, information_item_id, title)
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_reminder (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      action_item_id BIGINT NOT NULL,
                      user_id BIGINT NOT NULL,
                      remind_at TIMESTAMP NOT NULL,
                      status VARCHAR(32) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      sent_at TIMESTAMP,
                      UNIQUE (action_item_id, remind_at)
                    )
                    """);
            statement.execute("DELETE FROM user_reminder");
            statement.execute("DELETE FROM user_action_item");
            statement.execute("DELETE FROM user_information_state");
            statement.execute("DELETE FROM user_source_subscription");
            statement.execute("DELETE FROM information_item");
            statement.execute("DELETE FROM data_source");
            statement.execute("""
                    INSERT INTO data_source (id, name, source_type, base_url, enabled)
                    VALUES (1, '用户文本提交', 'USER_TEXT', 'campusmind://user-text-import', 1)
                    """);
            statement.execute("""
                    INSERT INTO data_source (id, name, source_type, base_url, enabled)
                    VALUES (9411, '软件学院创新创业通知公告', 'PUBLIC_WEB', 'https://ss.xju.edu.cn', 1)
                    """);
        }
        insertInformationItem(1L, "创新创业竞赛报名开放", "ACTIVE", "DETAIL_SUCCESS", "2026-07-09 10:00:00");
        insertInformationItem(2L, "软件学院通知", "UPDATED", "DETAIL_SUCCESS", "2026-07-08 10:00:00");
        insertInformationItem(3L, "解析失败通知", "FAILED", "DETAIL_FAILED", "2026-07-07 10:00:00");
    }

    @Test
    void informationFeedReturnsVisibleItems() throws Exception {
        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(2))
                .andExpect(jsonPath("$.data.items[0].title").value("创新创业竞赛报名开放"))
                .andExpect(jsonPath("$.data.items[0].readStatus").value("NEW"))
                .andExpect(jsonPath("$.data.items[0].originalUrl").value("https://ss.xju.edu.cn/info/1.htm"))
                .andExpect(jsonPath("$.data.items[0].aiStatus").value("PENDING"))
                .andExpect(jsonPath("$.data.hasMore").value(false));
    }

    @Test
    void sourceSubscriptionChangesOnlyThatUsersRankingAndSupportsSubscribedOnly() throws Exception {
        setSourceId(2L, 1L);
        subscribe(1L, 1L);

        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1").param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[0].id").value(2))
                .andExpect(jsonPath("$.data.items[0].recommendationScore").value(100))
                .andExpect(jsonPath("$.data.items[0].recommendReasons[0]").value("来自你订阅的软件学院创新创业通知公告"));

        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "2").param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[0].id").value(1));

        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1").param("mode", "SUBSCRIBED_ONLY").param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(1))
                .andExpect(jsonPath("$.data.items[0].id").value(2));
    }

    @Test
    void rankedCursorDoesNotRepeatItems() throws Exception {
        setSourceId(2L, 1L);
        subscribe(1L, 1L);
        var firstPage = mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1").param("size", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[0].id").value(2))
                .andExpect(jsonPath("$.data.hasMore").value(true))
                .andReturn();
        var json = com.jayway.jsonpath.JsonPath.parse(firstPage.getResponse().getContentAsString());

        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "1")
                        .param("cursor", json.read("$.data.nextCursor", String.class))
                        .param("cursorId", String.valueOf(json.read("$.data.nextCursorId", Number.class).longValue()))
                        .param("cursorSubscriptionMatch", String.valueOf(
                                json.read("$.data.nextSubscriptionMatch", Number.class).intValue())))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[0].id").value(1));
    }

    @Test
    void detailReturnsTraceableOriginalInformation() throws Exception {
        mockMvc.perform(get("/api/v1/information/items/1")
                        .header("X-User-Id", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.title").value("创新创业竞赛报名开放"))
                .andExpect(jsonPath("$.data.sourceName").value("软件学院创新创业通知公告"))
                .andExpect(jsonPath("$.data.originalUrl").value("https://ss.xju.edu.cn/info/1.htm"))
                .andExpect(jsonPath("$.data.contentHash").value("hash-1"))
                .andExpect(jsonPath("$.data.detailContent").value("竞赛报名正文，包含报名时间、截止时间和所需材料。"));
    }

    @Test
    void updateReadStatusPersistsUserState() throws Exception {
        mockMvc.perform(put("/api/v1/information/items/1/read-status")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"readStatus\":\"READ\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.readStatus").value("READ"));

        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[0].readStatus").value("READ"));
    }

    @Test
    void favoriteStatusIsStoredAndReturned() throws Exception {
        mockMvc.perform(put("/api/v1/information/items/1/read-status")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"readStatus\":\"READ\"}"))
                .andExpect(status().isOk());

        mockMvc.perform(put("/api/v1/information/items/1/read-status")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"readStatus\":\"FAVORITED\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.readStatus").value("FAVORITED"));

        mockMvc.perform(get("/api/v1/information/favorites").header("X-User-Id", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(1));
        mockMvc.perform(get("/api/v1/information/read-history").header("X-User-Id", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(1))
                .andExpect(jsonPath("$.data.items[0].readStatus").value("FAVORITED"));

        mockMvc.perform(put("/api/v1/information/items/1/read-status")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"readStatus\":\"READ\"}"))
                .andExpect(status().isOk());
        mockMvc.perform(get("/api/v1/information/favorites").header("X-User-Id", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(0));
    }

    @Test
    void createItemInsertsNewInformationItem() throws Exception {
        String body = """
                {
                  "title": "用户提交的讲座通知",
                  "detailContent": "某学院举办 AI 讲座，面向全校学生开放。",
                  "sourceName": "用户文本提交",
                  "sourceUrl": null,
                  "itemUrl": null,
                  "contentHash": "abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890"
                }
                """;
        mockMvc.perform(post("/api/v1/information")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.data").isNumber());

        // 验证条目已写入，可以在 feed 中查到
        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(3));
    }

    @Test
    void createItemIsIdempotentByContentHash() throws Exception {
        String body = """
                {
                  "title": "重复提交的通知",
                  "detailContent": "重复内容",
                  "sourceName": "用户文本提交",
                  "contentHash": "hash-1"
                }
                """;
        // hash-1 已在 setUp 中存在，应返回已有 ID 而不重复插入
        mockMvc.perform(post("/api/v1/information")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data").value(1));

        // feed 条目数不变
        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(2));
    }

    @Test
    void confirmedAiActionIsIdempotentAndCreatesOneReminder() throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     UPDATE information_item SET ai_status = 'SUCCESS', ai_need_review = FALSE,
                       ai_card_json = ? WHERE id = 1
                     """)) {
            String deadline = java.time.LocalDateTime.now().plusDays(10).withNano(0).toString();
            statement.setString(1, "{\"requiredActions\":[\"完成报名\"],\"registrationDeadline\":\"" + deadline + "\"}");
            statement.executeUpdate();
        }

        for (int i = 0; i < 2; i++) {
            mockMvc.perform(post("/api/v1/information/items/1/actions")
                            .header("X-User-Id", "1")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("{\"title\":\"完成报名\"}"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.data.status").value("CONFIRMED"));
        }

        mockMvc.perform(get("/api/v1/information/actions").header("X-User-Id", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.length()").value(1))
                .andExpect(jsonPath("$.data[0].title").value("完成报名"));
        org.junit.jupiter.api.Assertions.assertEquals(1, countRows("user_action_item"));
        org.junit.jupiter.api.Assertions.assertEquals(1, countRows("user_reminder"));
    }

    @Test
    void unreviewedAiActionCannotBeConfirmed() throws Exception {
        mockMvc.perform(post("/api/v1/information/items/1/actions")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"title\":\"完成报名\"}"))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.code").value("ACTION_NOT_CONFIRMABLE"));
    }

    private void insertInformationItem(Long id, String title, String itemStatus, String parseStatus, String fetchedAt)
            throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO information_item (
                       id, source_id, source_name, source_url, item_url, title,
                       publish_time, fetched_at, detail_content, content_hash,
                       item_status, parse_status, parse_error
                     ) VALUES (
                       ?, 9411, '软件学院创新创业通知公告', 'https://ss.xju.edu.cn/cxcy/tzgg.htm',
                       ?, ?, TIMESTAMP '2026-07-09 09:30:00', ?, ?, ?,
                       ?, ?, NULL
                     )
                     """)) {
            statement.setLong(1, id);
            statement.setString(2, "https://ss.xju.edu.cn/info/" + id + ".htm");
            statement.setString(3, title);
            statement.setString(4, fetchedAt);
            statement.setString(5, id == 1L ? "竞赛报名正文，包含报名时间、截止时间和所需材料。" : "学院通知正文。");
            statement.setString(6, "hash-" + id);
            statement.setString(7, itemStatus);
            statement.setString(8, parseStatus);
            statement.executeUpdate();
        }
    }

    private void setSourceId(long itemId, long sourceId) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(
                     "UPDATE information_item SET source_id = ? WHERE id = ?")) {
            statement.setLong(1, sourceId);
            statement.setLong(2, itemId);
            statement.executeUpdate();
        }
    }

    private void subscribe(long userId, long sourceId) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(
                     "INSERT INTO user_source_subscription (user_id, source_id, enabled) VALUES (?, ?, 1)")) {
            statement.setLong(1, userId);
            statement.setLong(2, sourceId);
            statement.executeUpdate();
        }
    }

    private int countRows(String table) throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             java.sql.ResultSet result = statement.executeQuery("SELECT COUNT(*) FROM " + table)) {
            result.next();
            return result.getInt(1);
        }
    }
}
