package cn.campusmind.feed.controller;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class InformationControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS information_item (
                      id BIGINT PRIMARY KEY,
                      source_id BIGINT NOT NULL,
                      source_name VARCHAR(128) NOT NULL,
                      source_url VARCHAR(1024) NOT NULL,
                      item_url VARCHAR(1024) NOT NULL,
                      title VARCHAR(512) NOT NULL,
                      publish_time TIMESTAMP,
                      fetched_at TIMESTAMP NOT NULL,
                      detail_content CLOB NOT NULL,
                      content_hash CHAR(64) NOT NULL,
                      item_status VARCHAR(32) NOT NULL,
                      parse_status VARCHAR(32) NOT NULL,
                      parse_error VARCHAR(1024),
                      ai_status VARCHAR(32) DEFAULT 'PENDING',
                      ai_event_type VARCHAR(32),
                      ai_summary CLOB,
                      ai_card_json CLOB,
                      ai_need_review BOOLEAN DEFAULT FALSE,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS user_information_state (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      item_id BIGINT NOT NULL,
                      read_status VARCHAR(32) NOT NULL,
                      first_seen_at TIMESTAMP NOT NULL,
                      read_at TIMESTAMP,
                      archived_at TIMESTAMP,
                      UNIQUE KEY uk_user_item_state (user_id, item_id)
                    )
                    """);
            statement.execute("DELETE FROM user_information_state");
            statement.execute("DELETE FROM information_item");
        }
        insertInformationItem(1L, "创新创业竞赛报名开放", "ACTIVE", "DETAIL_SUCCESS", "2026-07-09 10:00:00");
        insertInformationItem(2L, "软件学院通知", "UPDATED", "DETAIL_SUCCESS", "2026-07-08 10:00:00");
        insertInformationItem(3L, "解析失败通知", "FAILED", "DETAIL_FAILED", "2026-07-07 10:00:00");
    }

    @Test
    void informationFeedReturnsVisibleItems() throws Exception {
        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items.length()").value(2))
                .andExpect(jsonPath("$.data.items[0].title").value("创新创业竞赛报名开放"))
                .andExpect(jsonPath("$.data.items[0].readStatus").value("NEW"))
                .andExpect(jsonPath("$.data.items[0].originalUrl").value("https://ss.xju.edu.cn/info/1.htm"))
                .andExpect(jsonPath("$.data.items[0].aiStatus").value("PENDING"))
                .andExpect(jsonPath("$.data.hasMore").value(false));
    }

    @Test
    void detailReturnsTraceableOriginalInformation() throws Exception {
        mockMvc.perform(get("/api/v1/information/items/1")
                        .header("X-User-Id", "1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.title").value("创新创业竞赛报名开放"))
                .andExpect(jsonPath("$.data.sourceName").value("软件学院创新创业通知公告"))
                .andExpect(jsonPath("$.data.originalUrl").value("https://ss.xju.edu.cn/info/1.htm"))
                .andExpect(jsonPath("$.data.contentHash").value("hash-1"))
                .andExpect(jsonPath("$.data.detailContent").value("竞赛报名正文，包含报名时间、截止时间和所需材料。"));
    }

    @Test
    void updateReadStatusPersistsUserState() throws Exception {
        mockMvc.perform(put("/api/v1/information/items/1/read-status")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"readStatus\":\"READ\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.readStatus").value("READ"));

        mockMvc.perform(get("/api/v1/information/feed")
                        .header("X-User-Id", "1")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.items[0].readStatus").value("READ"));
    }

    @Test
    void favoriteStatusIsStoredAndReturned() throws Exception {
        mockMvc.perform(put("/api/v1/information/items/1/read-status")
                        .header("X-User-Id", "1")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"readStatus\":\"FAVORITED\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.readStatus").value("FAVORITED"));
    }

    private void insertInformationItem(Long id, String title, String itemStatus, String parseStatus, String fetchedAt)
            throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO information_item (
                       id, source_id, source_name, source_url, item_url, title,
                       publish_time, fetched_at, detail_content, content_hash,
                       item_status, parse_status, parse_error
                     ) VALUES (
                       ?, 9411, '软件学院创新创业通知公告', 'https://ss.xju.edu.cn/cxcy/tzgg.htm',
                       ?, ?, TIMESTAMP '2026-07-09 09:30:00', ?, ?, ?,
                       ?, ?, NULL
                     )
                     """)) {
            statement.setLong(1, id);
            statement.setString(2, "https://ss.xju.edu.cn/info/" + id + ".htm");
            statement.setString(3, title);
            statement.setString(4, fetchedAt);
            statement.setString(5, id == 1L ? "竞赛报名正文，包含报名时间、截止时间和所需材料。" : "学院通知正文。");
            statement.setString(6, "hash-" + id);
            statement.setString(7, itemStatus);
            statement.setString(8, parseStatus);
            statement.executeUpdate();
        }
    }
}
