package cn.campusmind.importing.controller;

import cn.campusmind.importing.application.CognitionClient;
import cn.campusmind.importing.application.CognitionResult;
import cn.campusmind.importing.application.EventServiceClient;
import cn.campusmind.importing.application.InformationServiceClient;
import cn.campusmind.importing.application.RainCookieStore;
import cn.campusmind.importing.application.RawDocumentService;
import cn.campusmind.importing.domain.RawDocument;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.data.redis.core.ValueOperations;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import javax.crypto.SecretKey;
import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.util.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.http.HttpHeaders.AUTHORIZATION;
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.math.BigDecimal;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class ImportControllerTest {

    private static final String SECRET = "test-secret-key-with-at-least-32-bytes";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @MockBean
    private RawDocumentService rawDocumentService;

    @MockBean
    private CognitionClient cognitionClient;

    @MockBean
    private RainCookieStore rainCookieStore;

    @MockBean
    private EventServiceClient eventServiceClient;

    @MockBean
    private InformationServiceClient informationServiceClient;

    @MockBean
    private StringRedisTemplate stringRedisTemplate;

    @BeforeEach
    void setUp() throws Exception {
        // mock Redis 速率限制
        ValueOperations<String, String> valueOps = org.mockito.Mockito.mock(ValueOperations.class);
        org.mockito.Mockito.when(stringRedisTemplate.opsForValue()).thenReturn(valueOps);
        org.mockito.Mockito.when(valueOps.increment(anyString())).thenReturn(1L);

        // mock EventServiceClient
        when(eventServiceClient.createEvent(
                any(), any(), any(), any(),
                any(), any(), any(), any(),
                any(), any(), any(), any(),
                any(), any(), any(), any()
        )).thenReturn(100L);

        // mock InformationServiceClient
        when(informationServiceClient.createItem(
                any(), any(), any(), any(), any(), any()
        )).thenReturn(200L);

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS import_task (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      user_id BIGINT NOT NULL,
                      import_type VARCHAR(64) NOT NULL,
                      task_status VARCHAR(32) NOT NULL,
                      raw_doc_id VARCHAR(64),
                      result_summary CLOB,
                      error_message VARCHAR(1024),
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      finished_at TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS campus_event (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      summary CLOB,
                      event_type VARCHAR(64) NOT NULL,
                      source_type VARCHAR(64) NOT NULL,
                      status VARCHAR(32) NOT NULL,
                      start_time TIMESTAMP,
                      end_time TIMESTAMP,
                      location VARCHAR(255),
                      organizer VARCHAR(255),
                      target_scope VARCHAR(1024),
                      tags VARCHAR(1024),
                      dedup_key CHAR(64),
                      vector_doc_id VARCHAR(128),
                      published_at TIMESTAMP,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS event_source_ref (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      event_id BIGINT NOT NULL,
                      source_id BIGINT,
                      raw_doc_id VARCHAR(64) NOT NULL,
                      source_url VARCHAR(1024),
                      source_title VARCHAR(255),
                      content_hash CHAR(64) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("DELETE FROM event_source_ref");
            statement.execute("DELETE FROM campus_event");
            statement.execute("DELETE FROM import_task");
        }
        when(rawDocumentService.save(any(RawDocument.class))).thenAnswer(invocation -> {
            RawDocument doc = invocation.getArgument(0);
            doc.setId("mongo-" + System.nanoTime());
            return doc;
        });
    }

    @Test
    void textImportGeneratesAiPredictedEvent() throws Exception {
        when(cognitionClient.extract(eq("USER_TEXT"), anyString())).thenReturn(candidate());

        mockMvc.perform(post("/api/v1/import/text")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("{\"text\":\"关于举办人工智能主题讲座的通知，时间2026-07-08 19:00，地点图书馆报告厅\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.data.status").value("SUCCESS"))
                .andExpect(jsonPath("$.data.taskId").exists())
                .andExpect(jsonPath("$.data.message").value("文本导入完成，已生成AI预测事件"));

        assertEquals(1, countRows("import_task", "task_status='SUCCESS'"), "任务应为SUCCESS");
        verify(eventServiceClient, times(1)).createEvent(
                any(), any(), any(), any(),
                any(), any(), any(), any(),
                any(), any(), eq("PUBLIC"), isNull(),
                any(), any(), any(), any()
        );
        verify(informationServiceClient, times(1)).createItem(
                any(), any(), any(), any(), any(), any()
        );
    }

    @Test
    void textImportMarksInformationCompensationWhenItemCreationFails() throws Exception {
        when(cognitionClient.extract(eq("USER_TEXT"), anyString())).thenReturn(candidate());
        when(informationServiceClient.createItem(any(), any(), any(), any(), any(), any())).thenReturn(null);

        mockMvc.perform(post("/api/v1/import/text")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("{\"text\":\"补偿测试文本\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.status").value("SUCCESS"));

        assertEquals(1, countRows("import_task", "result_summary LIKE '%information_item_creation_failed%'"));
    }

    @Test
    void textImportRecordsFailureWhenCognitionUnavailable() throws Exception {
        when(cognitionClient.extract(anyString(), anyString()))
                .thenThrow(new cn.campusmind.common.exception.BusinessException(
                        "COGNITION_UNAVAILABLE", "AI 认知服务暂不可用",
                        org.springframework.http.HttpStatus.BAD_GATEWAY));

        mockMvc.perform(post("/api/v1/import/text")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("{\"text\":\"测试文本\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.status").value("FAILED"));

        assertEquals(1, countRows("import_task", "task_status='FAILED'"), "任务应为FAILED");
    }

    @Test
    void rainJsonImportParsesItemsAndPersistsEvents() throws Exception {
        when(cognitionClient.extract(eq("RAIN_CLASSROOM"), anyString())).thenReturn(candidate());

        String rawJson = "{\"data\":{\"list\":[{\"courseName\":\"人工智能\",\"title\":\"作业一\",\"content\":\"提交实验报告\",\"deadline\":\"2026-07-10 23:59\",\"teacherName\":\"张老师\"}]}}";
        String body = "{\"dataType\":\"HOMEWORK\",\"rawJson\":" + jsonEscape(rawJson) + "}";

        mockMvc.perform(post("/api/v1/import/rain/json")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.status").value("SUCCESS"));

        assertEquals(1, countRows("import_task", "task_status='SUCCESS'"), "任务应为SUCCESS");
        verify(eventServiceClient, times(1)).createEvent(
                any(), any(), any(), any(),
                any(), any(), any(), any(),
                any(), any(), eq("PRIVATE"), eq(1L),
                any(), any(), any(), any()
        );
        verify(informationServiceClient, times(0)).createItem(
                any(), any(), any(), any(), any(), any()
        );
    }

    @Test
    void rainJsonImportAcceptsExporterFormat() throws Exception {
        when(cognitionClient.extract(eq("RAIN_CLASSROOM"), anyString())).thenReturn(candidate());
        String rawJson = "{\"schemaVersion\":1,\"provider\":\"RAIN_CLASSROOM\",\"items\":[{\"providerItemId\":\"42\",\"dataType\":\"HOMEWORK\",\"courseName\":\"软件工程\",\"title\":\"作业一\",\"content\":\"提交实验报告\",\"deadline\":\"2026-07-18 23:59\",\"teacherName\":\"张老师\"}]}";
        String body = "{\"dataType\":\"HOMEWORK\",\"rawJson\":" + jsonEscape(rawJson) + "}";

        mockMvc.perform(post("/api/v1/import/rain/json")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.status").value("SUCCESS"));
    }

    @Test
    void rainJsonImportRejectsUnsupportedExporterVersion() throws Exception {
        String rawJson = "{\"schemaVersion\":2,\"provider\":\"RAIN_CLASSROOM\",\"items\":[]}";
        String body = "{\"dataType\":\"HOMEWORK\",\"rawJson\":" + jsonEscape(rawJson) + "}";

        mockMvc.perform(post("/api/v1/import/rain/json")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("RAIN_JSON_INVALID"))
                .andExpect(jsonPath("$.message").value(org.hamcrest.Matchers.containsString("仅支持版本1")));
    }

    @Test
    void rainJsonImportRejectsWrongFieldType() throws Exception {
        String rawJson = "{\"schemaVersion\":1,\"provider\":\"RAIN_CLASSROOM\",\"items\":[{\"title\":123}]}";
        String body = "{\"dataType\":\"HOMEWORK\",\"rawJson\":" + jsonEscape(rawJson) + "}";

        mockMvc.perform(post("/api/v1/import/rain/json")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value(org.hamcrest.Matchers.containsString("字段title必须是字符串")));
    }

    @Test
    void rainJsonImportSkipsDuplicateItemsAndReportsCounts() throws Exception {
        when(cognitionClient.extract(eq("RAIN_CLASSROOM"), anyString())).thenReturn(candidate());
        String item = "{\"courseName\":\"软件工程\",\"title\":\"作业一\",\"content\":\"提交报告\"}";
        String rawJson = "{\"schemaVersion\":1,\"provider\":\"RAIN_CLASSROOM\",\"items\":[" + item + "," + item + "]}";
        String body = "{\"dataType\":\"HOMEWORK\",\"rawJson\":" + jsonEscape(rawJson) + "}";

        mockMvc.perform(post("/api/v1/import/rain/json")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content(body))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.message").value("雨课堂JSON导入完成，成功1条，跳过1条，失败0条"));

        assertEquals(1, countRows("import_task", "result_summary LIKE '%\"skipped\":1%'"));
        verify(cognitionClient, times(1)).extract(eq("RAIN_CLASSROOM"), anyString());
    }

    @Test
    void deleteRawDocumentOnlyDeletesTheCallingUsersDocument() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    INSERT INTO import_task (user_id, import_type, task_status, raw_doc_id, created_at)
                    VALUES (1, 'RAIN_JSON', 'SUCCESS', 'raw-delete', CURRENT_TIMESTAMP)
                    """);
        }
        long taskId = maxTaskId();

        mockMvc.perform(delete("/api/v1/import/tasks/{taskId}/raw", taskId)
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.message").value("原始数据已删除，私有事件仍保留"));

        verify(rawDocumentService).deleteOwned("raw-delete", 1L);
        assertEquals(1, countRows("import_task", "id=" + taskId + " AND raw_doc_id IS NULL"));
    }

    @Test
    void rainCookieImportIsDisabledByDefault() throws Exception {
        mockMvc.perform(post("/api/v1/import/rain/cookie")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("{\"cookie\":\"session=abc123; path=/\",\"importScopes\":[\"COURSE\",\"HOMEWORK\"],\"agreeOneTimeUse\":true}"))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value("RAIN_COOKIE_DISABLED"));

        verify(rainCookieStore, times(0)).save(anyString(), eq("session=abc123; path=/"));
    }

    @Test
    void rainCookieImportRejectsWhenDisabledBeforeReadingCredentials() throws Exception {
        mockMvc.perform(post("/api/v1/import/rain/cookie")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                .contentType(APPLICATION_JSON)
                .content("{\"cookie\":\"session=abc123\",\"agreeOneTimeUse\":false}"))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value("RAIN_COOKIE_DISABLED"));
    }

    @Test
    void importRejectsMissingToken() throws Exception {
        mockMvc.perform(post("/api/v1/import/text")
                        .contentType(APPLICATION_JSON)
                        .content("{\"text\":\"无令牌\"}"))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.code").value("UNAUTHORIZED"));
    }

    @Test
    void importRejectsBlankText() throws Exception {
        mockMvc.perform(post("/api/v1/import/text")
                        .header(AUTHORIZATION, bearerToken(1L, "alice", "STUDENT"))
                        .contentType(APPLICATION_JSON)
                        .content("{\"text\":\"\"}"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value("VALIDATION_ERROR"));
    }

    private CognitionResult candidate() {
        return new CognitionResult(
                "AI讲座通知", "LECTURE", "软件学院将举办AI主题讲座。",
                "2026-07-08 19:00", "2026-07-08 21:00",
                "图书馆报告厅", "软件学院",
                List.of("软件学院"), List.of("AI", "讲座"),
                false, "抽取成功");
    }

    private int countRows(String table, String where) throws Exception {
        String sql = "SELECT COUNT(*) FROM " + table + (where == null || where.isBlank() ? "" : " WHERE " + where);
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery(sql)) {
            rs.next();
            return rs.getInt(1);
        }
    }

    private long maxTaskId() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT MAX(id) FROM import_task")) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private static String jsonEscape(String value) {
        StringBuilder sb = new StringBuilder("\"");
        for (char c : value.toCharArray()) {
            switch (c) {
                case '"' -> sb.append("\\\"");
                case '\\' -> sb.append("\\\\");
                default -> sb.append(c);
            }
        }
        return sb.append("\"").toString();
    }

    private static String bearerToken(Long userId, String username, String role) {
        Instant now = Instant.now();
        SecretKey key = Keys.hmacShaKeyFor(SECRET.getBytes(StandardCharsets.UTF_8));
        String token = Jwts.builder()
                .issuer("campusmind-auth-test")
                .subject(String.valueOf(userId))
                .claim("username", username)
                .claim("role", role)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plusSeconds(3600)))
                .signWith(key)
                .compact();
        return "Bearer " + token;
    }
}
