package cn.campusmind.event.application;

import cn.campusmind.event.domain.EventSourceRef;
import cn.campusmind.event.domain.CampusEvent;
import cn.campusmind.event.infrastructure.mapper.CampusEventMapper;
import cn.campusmind.event.infrastructure.mapper.EventSourceRefMapper;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * 信息融合测试：验证同 contentHash 不同来源追加来源引用，以及同 dedupKey 复用事件。
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class EventFusionTest {

    @Autowired
    private EventCommandService eventCommandService;

    @Autowired
    private EventSourceRefMapper eventSourceRefMapper;

    @Autowired
    private CampusEventMapper campusEventMapper;

    @Autowired
    private DataSource dataSource;

    @BeforeEach
    void setUp() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS campus_event (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      summary CLOB,
                      event_type VARCHAR(64) NOT NULL,
                      source_type VARCHAR(64) NOT NULL,
                      status VARCHAR(32) NOT NULL,
                      start_time TIMESTAMP,
                      end_time TIMESTAMP,
                      location VARCHAR(255),
                      organizer VARCHAR(255),
                      target_scope VARCHAR(1024),
                      tags VARCHAR(1024),
                      dedup_key CHAR(64),
                      vector_doc_id VARCHAR(128),
                      published_at TIMESTAMP,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      visibility VARCHAR(16) DEFAULT 'PUBLIC',
                      owner_user_id BIGINT
                    )
                    """);
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS event_source_ref (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      event_id BIGINT NOT NULL,
                      source_id BIGINT,
                      raw_doc_id VARCHAR(64),
                      source_url VARCHAR(1024),
                      source_title VARCHAR(255),
                      content_hash CHAR(64) NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("DELETE FROM campus_event");
            statement.execute("DELETE FROM event_source_ref");
        }
    }

    @Test
    void shouldAppendSourceRefForSameContentHash() {
        String contentHash = "aaa";
        String dedupKey = "dedup-key-1";

        // 第一次来源：教务处
        Long eventId1 = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "讲座通知", "AI讲座摘要", "LECTURE", "PUBLIC_WEB",
                "2026-07-08 19:00:00", "2026-07-08 21:00:00",
                "图书馆", "软件学院", "[\"软件学院\"]", "[\"AI\"]",
                "PUBLIC", null, dedupKey,
                "raw-doc-1", "https://jwc.example.com/notice/1", contentHash
        ));

        // 第二次来源：辅导员通知，相同 contentHash
        Long eventId2 = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "讲座通知", "AI讲座摘要", "LECTURE", "PUBLIC_WEB",
                "2026-07-08 19:00:00", "2026-07-08 21:00:00",
                "图书馆", "软件学院", "[\"软件学院\"]", "[\"AI\"]",
                "PUBLIC", null, "different-dedup-key",
                "raw-doc-2", "https://辅导员.example.com/notice/2", contentHash
        ));

        // 应复用同一事件
        assertEquals(eventId1, eventId2, "同 contentHash 应复用同一事件");

        // 应有两条来源引用
        List<EventSourceRef> refs = eventSourceRefMapper.selectList(
                new LambdaQueryWrapper<EventSourceRef>()
                        .eq(EventSourceRef::getEventId, eventId1)
                        .orderByAsc(EventSourceRef::getCreatedAt));
        assertEquals(2, refs.size(), "应有两条来源引用");
        assertEquals("https://jwc.example.com/notice/1", refs.get(0).getSourceUrl());
        assertEquals("https://辅导员.example.com/notice/2", refs.get(1).getSourceUrl());
    }

    @Test
    void shouldReuseEventForSameDedupKey() {
        String dedupKey = "shared-dedup-key";

        // 第一次创建
        Long eventId1 = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "竞赛通知", "数学竞赛报名", "COMPETITION", "PUBLIC_WEB",
                null, null, null, null, null, null,
                "PUBLIC", null, dedupKey,
                "raw-doc-1", "https://example.com/source/1", "hash-1"
        ));

        // 第二次：相同 dedupKey，不同 contentHash
        Long eventId2 = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "竞赛通知", "数学竞赛报名", "COMPETITION", "PUBLIC_WEB",
                null, null, null, null, null, null,
                "PUBLIC", null, dedupKey,
                "raw-doc-2", "https://example.com/source/2", "hash-2"
        ));

        // 应复用同一事件
        assertEquals(eventId1, eventId2, "同 dedupKey 应复用同一事件");

        // 应有两条来源引用
        List<EventSourceRef> refs = eventSourceRefMapper.selectList(
                new LambdaQueryWrapper<EventSourceRef>()
                        .eq(EventSourceRef::getEventId, eventId1));
        assertEquals(2, refs.size(), "应有两条来源引用");
    }

    @Test
    void shouldCreateNewEventWhenNoMatch() {
        Long eventId1 = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "讲座A", "摘要A", "LECTURE", "PUBLIC_WEB",
                null, null, null, null, null, null,
                "PUBLIC", null, "dedup-a",
                "raw-1", "https://example.com/a", "hash-a"
        ));

        Long eventId2 = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "讲座B", "摘要B", "LECTURE", "PUBLIC_WEB",
                null, null, null, null, null, null,
                "PUBLIC", null, "dedup-b",
                "raw-2", "https://example.com/b", "hash-b"
        ));

        assertNotNull(eventId1);
        assertNotNull(eventId2);
        assertEquals(eventId1 + 1, eventId2, "不同事件应创建新记录");
    }

    @Test
    void privateContentHashMustNotFuseAcrossUsersAndUpsertMustUpdate() {
        String hash = "same-private-content";
        String dedup1 = "owner-1-event";
        Long owner1Event = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "软件工程", "第一次同步", "COURSE", "XJU_EHALL",
                "2026-09-07 10:00:00", "2026-09-07 11:40:00",
                "A101", "张老师", null, null,
                "PRIVATE", 1L, dedup1, null, "https://ehall.xju.edu.cn", hash));

        Long owner2Event = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "软件工程", "另一位用户", "COURSE", "XJU_EHALL",
                "2026-09-07 10:00:00", "2026-09-07 11:40:00",
                "A101", "张老师", null, null,
                "PUBLIC", 2L, "owner-2-event", null, "https://ehall.xju.edu.cn", hash));

        assertNotNull(owner1Event);
        assertNotNull(owner2Event);
        org.junit.jupiter.api.Assertions.assertNotEquals(owner1Event, owner2Event);

        Long updatedId = eventCommandService.upsertEvent(new EventCommandService.UpsertEventRequest(
                "软件工程", "地点已变更", "COURSE", "XJU_EHALL",
                "2026-09-07 10:00:00", "2026-09-07 11:40:00",
                "B202", "张老师", null, null,
                "PRIVATE", 1L, dedup1, null, "https://ehall.xju.edu.cn", "updated-hash"));

        assertEquals(owner1Event, updatedId);
        CampusEvent updated = campusEventMapper.selectById(owner1Event);
        assertEquals("B202", updated.getLocation());
        assertEquals("PRIVATE", updated.getVisibility());
        assertEquals(1L, updated.getOwnerUserId());
    }
}
