SET NAMES utf8mb4;

USE campusmind;

ALTER TABLE information_item
  ADD COLUMN IF NOT EXISTS ai_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SUCCESS/REVIEW/FAILED',
  ADD COLUMN IF NOT EXISTS ai_event_type VARCHAR(32) NULL COMMENT '智能体识别的信息类型',
  ADD COLUMN IF NOT EXISTS ai_summary TEXT NULL COMMENT '智能精简摘要',
  ADD COLUMN IF NOT EXISTS ai_card_json JSON NULL COMMENT '智能体结构化信息卡片',
  ADD COLUMN IF NOT EXISTS ai_confidence DECIMAL(5,4) NULL COMMENT '智能提取置信度',
  ADD COLUMN IF NOT EXISTS ai_need_review TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需要人工复核',
  ADD COLUMN IF NOT EXISTS ai_error VARCHAR(1024) NULL COMMENT '智能提取失败原因',
  ADD COLUMN IF NOT EXISTS ai_processed_at DATETIME NULL COMMENT '智能提取完成时间';
