package cn.campusmind.auth.controller;

import cn.campusmind.auth.application.AuthSessionService;
import cn.campusmind.auth.domain.UserRole;
import cn.campusmind.auth.domain.UserStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.blankOrNullString;
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.when;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class AuthControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private DataSource dataSource;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @MockitoBean
    private AuthSessionService authSessionService;

    private long aliceId;

    @BeforeEach
    void setUp() throws Exception {
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE IF NOT EXISTS `user` (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      username VARCHAR(64) NOT NULL UNIQUE,
                      phone VARCHAR(32),
                      email VARCHAR(255) UNIQUE,
                      password_hash VARCHAR(255) NOT NULL,
                      role VARCHAR(32) NOT NULL,
                      status TINYINT NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);
            statement.execute("DELETE FROM `user`");
        }

        insertUser("alice", "password123", UserRole.STUDENT, UserStatus.ENABLED);
        insertUser("disabled", "password123", UserRole.STUDENT, UserStatus.DISABLED);
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("SELECT id FROM `user` WHERE username = ?")) {
            statement.setString(1, "alice");
            try (var result = statement.executeQuery()) {
                result.next();
                aliceId = result.getLong(1);
            }
        }
        when(authSessionService.create(anyLong())).thenAnswer(invocation ->
                new AuthSessionService.Session(
                        invocation.getArgument(0), "session-id", "refresh-token",
                        java.time.Instant.now().plusSeconds(3600)
                ));
    }

    @Test
    void loginReturnsJwtForValidCredentials() throws Exception {
        mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"username":"alice","password":"password123"}
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.data.accessToken", not(blankOrNullString())))
                .andExpect(jsonPath("$.data.refreshToken").value("refresh-token"))
                .andExpect(jsonPath("$.data.tokenType").value("Bearer"))
                .andExpect(jsonPath("$.data.user.username").value("alice"))
                .andExpect(jsonPath("$.data.user.role").value("STUDENT"));
    }

    @Test
    void studentCanRegisterAndWebLoginUsesHttpOnlyCookies() throws Exception {
        mockMvc.perform(post("/api/v1/auth/register")
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"username":"new_student","email":"student@example.test","password":"password123"}
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.user.role").value("STUDENT"));

        mockMvc.perform(post("/api/v1/auth/web/login")
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"username":"alice","password":"password123"}
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.accessToken").doesNotExist())
                .andExpect(result -> {
                    var cookies = result.getResponse().getHeaders("Set-Cookie");
                    assertTrue(cookies.stream().anyMatch(value -> value.contains("campusmind_access=") && value.contains("HttpOnly")));
                    assertTrue(cookies.stream().anyMatch(value -> value.contains("campusmind_refresh=") && value.contains("HttpOnly")));
                });
    }

    @Test
    void loginRejectsWrongPassword() throws Exception {
        mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"username":"alice","password":"wrong"}
                                """))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.code").value("INVALID_CREDENTIALS"));
    }

    @Test
    void loginRejectsDisabledUser() throws Exception {
        mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"username":"disabled","password":"password123"}
                                """))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.success").value(false))
                .andExpect(jsonPath("$.code").value("USER_DISABLED"));
    }

    @Test
    void refreshRotatesTokenAndReturnsNewSession() throws Exception {
        when(authSessionService.rotate("refresh-old")).thenReturn(new AuthSessionService.Session(
                aliceId, "session-new", "refresh-new", java.time.Instant.now().plusSeconds(3600)
        ));

        mockMvc.perform(post("/api/v1/auth/refresh")
                        .contentType(APPLICATION_JSON)
                        .content("""
                                {"refreshToken":"refresh-old"}
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.accessToken", not(blankOrNullString())))
                .andExpect(jsonPath("$.data.refreshToken").value("refresh-new"));
    }

    private void insertUser(String username, String password, UserRole role, UserStatus status) throws Exception {
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     INSERT INTO `user` (username, password_hash, role, status)
                     VALUES (?, ?, ?, ?)
                     """)) {
            statement.setString(1, username);
            statement.setString(2, passwordEncoder.encode(password));
            statement.setString(3, role.name());
            statement.setInt(4, status.code());
            statement.executeUpdate();
        }
    }
}
